export const DB_NAME = "Campus_Engage";

export const EVENT_CATEGORIES = ["TECH", "CULTURAL", "SPORTS", "ACADEMIC", "WORKSHOP"];

// export const EVENT_STATUS = ["UPCOMING", "ONGOING", "COMPLETED", "CANCELLED"];

export const REGISTRATION_STATUS = ["REGISTERED", "ATTENDED", "ABSENT", "CANCELLED"];

export const EVENT_STATUS = {
    UPCOMING: "UPCOMING",
    ONGOING: "ONGOING",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    DELETED: "DELETED" // Optional, if you do soft deletes
};

export const PAYMENT_STATUS = ["PENDING", "CONFIRMED", "FAILED", "REFUNDED", "CANCELLED"];